- Makefile
change the key size from `4096` to `2048`
allow the key to be used by ALB & NLB
> change key size (4096 -> 2048)

- lib/otelcol.yaml
> add logs pipeline

- Makefile
> populate cert arn for CR values file

- README.md
- lib/otelcol.yaml
- make/Makefile-local-install
- make/Makefile-local-recipes
- make/Makefile-local-uninstall
- templates/prometheus-values.yaml
> chore: make local and aws installations consistent

- make/Makefile-local-install
- make/Makefile-local-uninstall
utilize the `mydecisive` helm chart for `opentelemetry-operator`
> chore: use mydecisive helm repo for opentelemetry-operator

- values/otelcol-config.yaml
> fix: update otel collector config to contain logs

- lib/decisive-engine-aws-cdk-stack.ts
- make/Makefile-local-install
- test/decisive-engine-aws-cdk.test.ts
> Add datalyzer to deployment

- values/params-values-otel.yaml
> added autoscaler section to Otelcol CR

- make/Makefile-local-install
no
remove unneeded dependencies
`make create-mdai`
no
`make create-mdai` is successful
> chore: remove unneeded deps

- jobs/cronjob-logs.yaml
- jobs/job-logs.yaml
- jobs/job-metrics.yaml
- jobs/job-traces.yaml
Add MLT jobs and update hardcoded values for cronjob-logs
> task: Add MLT jobs and update hardcoded values for cronjob-logs

- make/Makefile-local-install
- make/Makefile-local-recipes
fix: adding missing commands for semi-auto install
> fix: adding missing commands for semi-auto install

- Makefile
Removing typo in karpenter config
> fix: removing typo for command

- .gitignore
- Makefile
- kubectl-cfg.go
1. Fixing a few out-of-date/incompatible commands for CDK integration
2. Adding protection to karpenter make targets
> fix: cdk incompatible command and adding reassurance to karpenter commands

- templates/mdai-operator.yaml
> chore: fix yaml quoting issue

- Makefile
> fix for make cert target

- lib/decisive-engine-aws-cdk-stack.ts
- make/Makefile-local-install
- templates/mdai-operator.yaml
- templates/prometheus-values.yaml
- test/decisive-engine-aws-cdk.test.ts
> Add datalyzer scrape and upgrade charts

- lib/decisive-engine-aws-cdk-stack.ts
- make/Makefile-local-install
- test/decisive-engine-aws-cdk.test.ts
> update mdai-console to 0.2.0 in relevant places

- lib/decisive-engine-aws-cdk-stack.ts
- make/Makefile-local-install
- test/decisive-engine-aws-cdk.test.ts
> mdai-console 0.2.1

- lib/decisive-engine-aws-cdk-stack.ts
- make/Makefile-local-install
- test/decisive-engine-aws-cdk.test.ts
> mdai-console 0.2.2

- Makefile
Improvement to return a meaningful error message 
Better error handling
Make file
No
Run make cert
> make error handling

- README.md
Minor fix for moving installation instructions to docs.
> fix: updates to remove install guide and point to docs

- Makefile
> rollback checks
